### ISSUE TITLE
Most of this shit is ass

### ISSUE THREAD

**Issue by lunarcleint** [kittstone/psych-scriptlibs#3]
MOST OF THE TIME THEY DO NOT WORK AS THE USE OUTDATED FUNCTIONS EX: require/os
THEY DO THINGS THAT CAN BE DONE MUCH EASIER BY JUST USING A FUNCTION EX: raf/ObjectUtil Screencenter (already a 
function from psych)
THEY MAKE NO SENSE AND USE WEIRD CODE: EX: voidless/FunkyMouse general bad coding
LITERALLY JUST SETTING VARIABLES: EX: raf/LuaWindow just setting the vars
CODE THAT LOGICALLY DOESN'T WORK: EX: raf/LuaSave setting save variables won't work unless you call flush on the FlxSave

**Comment by fluffabun15** [comment]
jesus christ calm down

**Comment by fluffabun15** [comment]
most of this shit isnt even meant to be like actually used in mods and shit, and even if it is, we're still doing this shit for fun

**Comment by fluffabun15** [comment]
read the fucking readme please, also this hasnt been updated in like weeks tf you doing here
